# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/holger/lib/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.3.0/cmake-3.23.1-cdcquv2g5xfuyrh734xpukw5uroup7cr/bin/cmake

# The command to remove a file.
RM = /home/holger/lib/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.3.0/cmake-3.23.1-cdcquv2g5xfuyrh734xpukw5uroup7cr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/holger/src/physics/vellamo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/holger/src/physics/vellamo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/holger/lib/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.3.0/cmake-3.23.1-cdcquv2g5xfuyrh734xpukw5uroup7cr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/holger/lib/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.3.0/cmake-3.23.1-cdcquv2g5xfuyrh734xpukw5uroup7cr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/holger/src/physics/vellamo/CMakeFiles /home/holger/src/physics/vellamo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/holger/src/physics/vellamo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vellamo1d

# Build rule for target.
vellamo1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vellamo1d
.PHONY : vellamo1d

# fast build rule for target.
vellamo1d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/build
.PHONY : vellamo1d/fast

#=============================================================================
# Target rules for targets named vellamo2d

# Build rule for target.
vellamo2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vellamo2d
.PHONY : vellamo2d

# fast build rule for target.
vellamo2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/build
.PHONY : vellamo2d/fast

#=============================================================================
# Target rules for targets named vellamo3d

# Build rule for target.
vellamo3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vellamo3d
.PHONY : vellamo3d

# fast build rule for target.
vellamo3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/build
.PHONY : vellamo3d/fast

huerto/constants.o: huerto/constants.cpp.o
.PHONY : huerto/constants.o

# target to build an object file
huerto/constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/constants.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/constants.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/constants.cpp.o
.PHONY : huerto/constants.cpp.o

huerto/constants.i: huerto/constants.cpp.i
.PHONY : huerto/constants.i

# target to preprocess a source file
huerto/constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/constants.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/constants.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/constants.cpp.i
.PHONY : huerto/constants.cpp.i

huerto/constants.s: huerto/constants.cpp.s
.PHONY : huerto/constants.s

# target to generate assembly for a file
huerto/constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/constants.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/constants.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/constants.cpp.s
.PHONY : huerto/constants.cpp.s

huerto/hydrodynamics/euler/adiabatic_knp.o: huerto/hydrodynamics/euler/adiabatic_knp.cpp.o
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.o

# target to build an object file
huerto/hydrodynamics/euler/adiabatic_knp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.o
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.cpp.o

huerto/hydrodynamics/euler/adiabatic_knp.i: huerto/hydrodynamics/euler/adiabatic_knp.cpp.i
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.i

# target to preprocess a source file
huerto/hydrodynamics/euler/adiabatic_knp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.i
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.cpp.i

huerto/hydrodynamics/euler/adiabatic_knp.s: huerto/hydrodynamics/euler/adiabatic_knp.cpp.s
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.s

# target to generate assembly for a file
huerto/hydrodynamics/euler/adiabatic_knp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/adiabatic_knp.cpp.s
.PHONY : huerto/hydrodynamics/euler/adiabatic_knp.cpp.s

huerto/hydrodynamics/euler/euler_knp.o: huerto/hydrodynamics/euler/euler_knp.cpp.o
.PHONY : huerto/hydrodynamics/euler/euler_knp.o

# target to build an object file
huerto/hydrodynamics/euler/euler_knp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.o
.PHONY : huerto/hydrodynamics/euler/euler_knp.cpp.o

huerto/hydrodynamics/euler/euler_knp.i: huerto/hydrodynamics/euler/euler_knp.cpp.i
.PHONY : huerto/hydrodynamics/euler/euler_knp.i

# target to preprocess a source file
huerto/hydrodynamics/euler/euler_knp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.i
.PHONY : huerto/hydrodynamics/euler/euler_knp.cpp.i

huerto/hydrodynamics/euler/euler_knp.s: huerto/hydrodynamics/euler/euler_knp.cpp.s
.PHONY : huerto/hydrodynamics/euler/euler_knp.s

# target to generate assembly for a file
huerto/hydrodynamics/euler/euler_knp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/euler/euler_knp.cpp.s
.PHONY : huerto/hydrodynamics/euler/euler_knp.cpp.s

huerto/hydrodynamics/hydro_fields.o: huerto/hydrodynamics/hydro_fields.cpp.o
.PHONY : huerto/hydrodynamics/hydro_fields.o

# target to build an object file
huerto/hydrodynamics/hydro_fields.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/hydro_fields.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/hydro_fields.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/hydro_fields.cpp.o
.PHONY : huerto/hydrodynamics/hydro_fields.cpp.o

huerto/hydrodynamics/hydro_fields.i: huerto/hydrodynamics/hydro_fields.cpp.i
.PHONY : huerto/hydrodynamics/hydro_fields.i

# target to preprocess a source file
huerto/hydrodynamics/hydro_fields.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/hydro_fields.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/hydro_fields.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/hydro_fields.cpp.i
.PHONY : huerto/hydrodynamics/hydro_fields.cpp.i

huerto/hydrodynamics/hydro_fields.s: huerto/hydrodynamics/hydro_fields.cpp.s
.PHONY : huerto/hydrodynamics/hydro_fields.s

# target to generate assembly for a file
huerto/hydrodynamics/hydro_fields.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/huerto/hydrodynamics/hydro_fields.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/huerto/hydrodynamics/hydro_fields.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/huerto/hydrodynamics/hydro_fields.cpp.s
.PHONY : huerto/hydrodynamics/hydro_fields.cpp.s

src/diagnostic.o: src/diagnostic.cpp.o
.PHONY : src/diagnostic.o

# target to build an object file
src/diagnostic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/diagnostic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/diagnostic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/diagnostic.cpp.o
.PHONY : src/diagnostic.cpp.o

src/diagnostic.i: src/diagnostic.cpp.i
.PHONY : src/diagnostic.i

# target to preprocess a source file
src/diagnostic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/diagnostic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/diagnostic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/diagnostic.cpp.i
.PHONY : src/diagnostic.cpp.i

src/diagnostic.s: src/diagnostic.cpp.s
.PHONY : src/diagnostic.s

# target to generate assembly for a file
src/diagnostic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/diagnostic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/diagnostic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/diagnostic.cpp.s
.PHONY : src/diagnostic.cpp.s

src/vellamo.o: src/vellamo.cpp.o
.PHONY : src/vellamo.o

# target to build an object file
src/vellamo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/vellamo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/vellamo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/vellamo.cpp.o
.PHONY : src/vellamo.cpp.o

src/vellamo.i: src/vellamo.cpp.i
.PHONY : src/vellamo.i

# target to preprocess a source file
src/vellamo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/vellamo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/vellamo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/vellamo.cpp.i
.PHONY : src/vellamo.cpp.i

src/vellamo.s: src/vellamo.cpp.s
.PHONY : src/vellamo.s

# target to generate assembly for a file
src/vellamo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo1d.dir/build.make CMakeFiles/vellamo1d.dir/src/vellamo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo2d.dir/build.make CMakeFiles/vellamo2d.dir/src/vellamo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vellamo3d.dir/build.make CMakeFiles/vellamo3d.dir/src/vellamo.cpp.s
.PHONY : src/vellamo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vellamo1d"
	@echo "... vellamo2d"
	@echo "... vellamo3d"
	@echo "... huerto/constants.o"
	@echo "... huerto/constants.i"
	@echo "... huerto/constants.s"
	@echo "... huerto/hydrodynamics/euler/adiabatic_knp.o"
	@echo "... huerto/hydrodynamics/euler/adiabatic_knp.i"
	@echo "... huerto/hydrodynamics/euler/adiabatic_knp.s"
	@echo "... huerto/hydrodynamics/euler/euler_knp.o"
	@echo "... huerto/hydrodynamics/euler/euler_knp.i"
	@echo "... huerto/hydrodynamics/euler/euler_knp.s"
	@echo "... huerto/hydrodynamics/hydro_fields.o"
	@echo "... huerto/hydrodynamics/hydro_fields.i"
	@echo "... huerto/hydrodynamics/hydro_fields.s"
	@echo "... src/diagnostic.o"
	@echo "... src/diagnostic.i"
	@echo "... src/diagnostic.s"
	@echo "... src/vellamo.o"
	@echo "... src/vellamo.i"
	@echo "... src/vellamo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

